1. Solve the given 0/1 knapsack problem by considering the following points:
Name Weight Value
A 45 3
B 40 5
C 50 8
D 90 10
Chromosome is a 4-bit string. – {xA xB xC xD}
Population size = 4, Maximum Capacity of the bag (W) = 100.
First two fittest chromosomes selected as it is. 3rd and 4th fittest use for one-point crossover in
the middle followed by single bit mutation of first offspring.
Bits chosen for mutation follows this cyclic order (xD, xC, xB, xA).
Initial population: {1 1 1 1, 1 0 0 0, 1 0 1 0, 1 0 0 1}.
Output the result after 10 iterations.

In [1]:
import numpy as np

# Define the items as (weight, value)
items = {"A": (45, 3), "B": (40, 5), "C": (50, 8), "D": (90, 10)}
max_capacity = 100
mutation_order = ['D', 'C', 'B', 'A']
population_size = 4
num_iterations = 10

# Initial population
population = np.array([[1, 1, 1, 1],
                       [1, 0, 0, 0],
                       [1, 0, 1, 0],
                       [1, 0, 0, 1]])

def calculate_fitness(chromosome):
    total_weight = sum(chromosome[i] * item[0] for i, item in enumerate(items.values()))
    total_value = sum(chromosome[i] * item[1] for i, item in enumerate(items.values()))
    if total_weight <= max_capacity:
        return total_value
    else:
        return 0  # Disqualify over-capacity chromosomes

def select(population):
    fitness_scores = [calculate_fitness(chromosome) for chromosome in population]
    sorted_indices = np.argsort(fitness_scores)[::-1]  # Sort in descending order
    return population[sorted_indices[:2]], population[sorted_indices[2:]]  # Return top 2 and the rest

def crossover(chromosome1, chromosome2):
    crossover_point = len(chromosome1) // 2
    offspring1 = np.concatenate([chromosome1[:crossover_point], chromosome2[crossover_point:]])
    offspring2 = np.concatenate([chromosome2[:crossover_point], chromosome1[crossover_point:]])
    return offspring1, offspring2

def mutate(chromosome, mutation_cycle):
    mutation_index = mutation_order.index(mutation_cycle)  # Find the index for mutation
    # Flip the bit
    chromosome[mutation_index] = 0 if chromosome[mutation_index] == 1 else 1
    return chromosome

def genetic_algorithm(population, num_iterations):
    mutation_cycle_index = 0
    for iteration in range(num_iterations):
        # Selection
        fittest, rest = select(population)
        
        # Crossover
        offspring1, offspring2 = crossover(rest[0], rest[1])
        
        # Mutation (only the first offspring according to the problem statement)
        offspring1 = mutate(offspring1, mutation_order[mutation_cycle_index])
        mutation_cycle_index = (mutation_cycle_index + 1) % len(mutation_order)  # Cycle the mutation
        
        # Create new population
        population = np.array([fittest[0], fittest[1], offspring1, offspring2])
        
        print(f"Iteration {iteration + 1}, Best Fitness: {calculate_fitness(fittest[0])}")
    
    return population

# Run the genetic algorithm
final_population = genetic_algorithm(population, num_iterations)
print("Final population:")
print(final_population)


Iteration 1, Best Fitness: 11
Iteration 2, Best Fitness: 11
Iteration 3, Best Fitness: 11
Iteration 4, Best Fitness: 11
Iteration 5, Best Fitness: 11
Iteration 6, Best Fitness: 11
Iteration 7, Best Fitness: 11
Iteration 8, Best Fitness: 11
Iteration 9, Best Fitness: 11
Iteration 10, Best Fitness: 11
Final population:
[[1 0 1 0]
 [0 0 0 1]
 [0 1 1 1]
 [0 1 0 0]]


2. A thief enters a house for robbing it. He can carry a maximal weight of 9 kg into his bag. There
are 4 items in the house with the following weights and values. The thief has to plan the items he
should take to maximize the total value if he either takes the item completely or leaves it
completely?
Item Item Name Weight (in Kg) Value (in $)
A Mirror 2 3
B Silver Nugget 3 5
C Painting 4 7
D Vase 5 9
The problem is solved using Genetic Algorithm with population size 4 and each individual
encoded as {XA, XB, XC, XD} where Xi ={0,1 } and i=A, B, C, D.
Consider initial population as 1111, 1000, 1010, and 1001.
Generate the population for next iteration as follows: Select the 1st and 2nd fittest individual as it
is in the next iteration. Apply 1-point crossover in the middle between 3rd and 4th fittest
chromosome followed by single bit mutation of first offspring (produced through crossover). Bit
chosen for mutation follows this cyclic order {XC,XA,XD,XB}
Output the result after four iterations.

In [2]:
import numpy as np

# Define the items as (weight, value)
items = {"A": (2, 3), "B": (3, 5), "C": (4, 7), "D": (5, 9)}
max_capacity = 9
mutation_order = ['C', 'A', 'D', 'B']
population_size = 4
num_iterations = 4

# Initial population
population = np.array([[1, 1, 1, 1],
                       [1, 0, 0, 0],
                       [1, 0, 1, 0],
                       [1, 0, 0, 1]])

def calculate_fitness(chromosome):
    total_weight = sum(chromosome[i] * item[0] for i, item in enumerate(items.values()))
    total_value = sum(chromosome[i] * item[1] for i, item in enumerate(items.values()))
    if total_weight <= max_capacity:
        return total_value
    else:
        return 0  # Disqualify over-capacity chromosomes

def select(population):
    fitness_scores = [calculate_fitness(chromosome) for chromosome in population]
    sorted_indices = np.argsort(fitness_scores)[::-1]  # Sort in descending order
    return population[sorted_indices[:2]], population[sorted_indices[2:]]  # Return top 2 and the rest

def crossover(chromosome1, chromosome2):
    crossover_point = len(chromosome1) // 2
    offspring1 = np.concatenate([chromosome1[:crossover_point], chromosome2[crossover_point:]])
    offspring2 = np.concatenate([chromosome2[:crossover_point], chromosome1[crossover_point:]])
    return offspring1, offspring2

def mutate(chromosome, mutation_cycle):
    mutation_index = mutation_order.index(mutation_cycle)  # Find the index for mutation
    # Flip the bit
    chromosome[mutation_index] = 0 if chromosome[mutation_index] == 1 else 1
    return chromosome

def genetic_algorithm(population, num_iterations):
    mutation_cycle_index = 0
    for iteration in range(num_iterations):
        # Selection
        fittest, rest = select(population)
        
        # Crossover
        offspring1, offspring2 = crossover(rest[0], rest[1])
        
        # Mutation (only the first offspring according to the problem statement)
        offspring1 = mutate(offspring1, mutation_order[mutation_cycle_index])
        mutation_cycle_index = (mutation_cycle_index + 1) % len(mutation_order)  # Cycle the mutation
        
        # Create new population
        population = np.array([fittest[0], fittest[1], offspring1, offspring2])
        
        print(f"Iteration {iteration + 1}, Best Fitness: {calculate_fitness(fittest[0])}")
    
    return population

# Run the genetic algorithm
final_population = genetic_algorithm(population, num_iterations)
print("Final population:")
print(final_population)


Iteration 1, Best Fitness: 12
Iteration 2, Best Fitness: 16
Iteration 3, Best Fitness: 16
Iteration 4, Best Fitness: 16
Final population:
[[0 0 1 1]
 [1 1 1 0]
 [1 0 0 0]
 [1 1 1 0]]
